# -*- coding: utf-8 -*-
"""fibonacci check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eo5flwBVdd-eK8MWJj858zSGK2egELsa
"""

import math

print('Check if a number is in the fibonacci sequence:')
fib_input = int(input())

fib_check1 = (5*(fib_input**2) + 4)
fib_check2 = (5*(fib_input**2) - 4)


sq_check1 = math.sqrt(fib_check1)
sq_check2 = math.sqrt(fib_check2)

if sq_check1.is_integer() or sq_check2.is_integer() is True:
  print('Congrats your number is within the fibonacci sequence')
else:
  print('Sorry that is not within the fibonacci sequence')

