# -*- coding: utf-8 -*-
"""random number generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXyQ_4SZ7PthJVFl_QJqNUqeTdMG2AsL
"""

import random
n = random.randint(0,100)
print(n)
print('input a number')
user_input_correct = False

while user_input_correct == False:
  try:
    user_input = int(input())
    user_input_correct = True
  except:
    print('Please enter a correct integer')

while n != user_input:

  if n > user_input:
    print('a little higher')
    user_input = int(input())

  elif n < user_input:
    print('a little lower')
    user_input = int(input())

if user_input == n:
  print('congrats you got the right number')